language: sh

os:
  - linux

dist: xenial

install:
  - curl -L https://deno.land/x/install/install.sh | sh -s v1.6.0
  - export PATH="$HOME/.deno/bin:$PATH"

branches:
  only:
  - master

cache:
  directories:
    - '$HOME/.deno'

script:
  - deno --version
  - deno run --allow-read --allow-env --allow-net twitter/uploader.ts
