language: node_js

os:
  - linux

dist: xenial

node_js:
  - 12.16.0

branches:
  only:
  - master

cache:
  directories:
  - node_modules

before_script:
  - npm ci

script:
  - node tweetUploader.js